// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://akgfecebshyseanlnvom.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFrZ2ZlY2Vic2h5c2Vhbmxudm9tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY1NTA1NzQsImV4cCI6MjA1MjEyNjU3NH0.E3DBAZsqMRQjW3SjbNsQFBrhEOfqoKBJN1dFqrQoE-E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);